site_name: 信奥爱好者 OIer Fans # 设置网站名称

# 导航目录
nav:
  - 首页: index.md
  - 信息学奥林匹克竞赛 OI: 
      - 关于NOI: noi\introduction.md
      - 竞赛大纲: noi\outline.md
      - 入门级CSP-J: junior\junior.md
      - 提高级CSP-S: senior\senior.md
      - NOI级: noi\noiji.md
  - 大模型能力认证 LMCC: 
      - 关于LMCC: lmcc\lmcc.md
      - 认证大纲: lmcc\outline.md
#  - 相关网站: websitelist.md
#  - 相关书籍: booklist.md

# Theme 主题设置
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
  language: 'zh'
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  palette: # 白天模式/黑夜模式
    # Toggle light mode
    - scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Toggle dark mode
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode

# 设置底部
copyright: 'Copyright &copy; 2024 - 2025 noi.fan All Rights Reserved.'
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<admin@oier.fans>
      name: 联系邮箱
  # generator: false # 移除生成标记 Made with Material for MkDocs